### ISSUE TITLE
OpenSearch releases from 2.10 > 2.14

### ISSUE THREAD

**Issue by back-2-95** [EvidentSolutions/opensearch-analysis-raudikko#1]
Could you create releases for OpenSearch versions from 2.10 to 2.14?

Thanks!

**Comment by back-2-95** [comment]
I created a PR for this but I'm not sure if all I did is enough.

**Comment by komu** [comment]
Since the actual code didn't change in any way and is compatible with all the releases, it doesn't even require a PR, I just ran the [add-release-archive workflow](https://github.com/EvidentSolutions/opensearch-analysis-raudikko/actions/workflows/add-release-archive.yaml) to build the code against new versions and add the artifacts to the existing [0.1.0 release](https://github.com/EvidentSolutions/opensearch-analysis-raudikko/releases/tag/v0.1.0).

I did change the matrix in `build.yaml  to make sure that we build against the latest tested version `2.14.0` as well as the earliest `2.5.0` and I changed `release.yaml` to build releases for the latest five versions. But that only applies when we make actual changes to the code and need to make new releases. And by that time there are probably new OpenSearch versions out there and that needs to be changed anyway.

Anyway, your bits should be on the [release page](https://github.com/EvidentSolutions/opensearch-analysis-raudikko/releases) and you should be good to go.

Thanks for the issue and for the PR!

**Comment by back-2-95** [comment]
Thank you!
